spring.application.name=ecoflow

# ==========================================
# 1. Configurações de Conexão com o Oracle (free:latest)
# ==========================================
spring.datasource.url=jdbc:oracle:thin:@localhost:1522/FREE
spring.datasource.username=${APP_DB_USER}
spring.datasource.password=${APP_DB_PWD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ==========================================
# 2. Configurações do Flyway (Migrações)
# ==========================================

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# ==========================================
# 3. Configurações do JPA / Hibernate
# ==========================================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true