ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER ecoflowusr IDENTIFIED BY "ecoflow123" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER TO ecoflowusr;

ALTER SYSTEM DISABLE RESTRICTED SESSION;