ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER ecoflow IDENTIFIED BY "ecoflow123" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER TO ecoflow;