ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER ecoflow IDENTIFIED BY "ecoflow" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE TRIGGER, CREATE PROCEDURE TO ecoflow;

ALTER USER ecoflow QUOTA UNLIMITED ON USERS;

