CREATE TABLE SETOR (
    ID_SETOR NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME_SETOR VARCHAR2(100) NOT NULL,
    DESCRICAO VARCHAR2(200),
    RESPONSAVEL VARCHAR2(100) NOT NULL,
    DT_CADASTRO DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE TIPO_RESIDUO (
    ID_TIPO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME_RESIDUO VARCHAR2(100) NOT NULL,
    CLASSIFICACAO VARCHAR2(20) NOT NULL,
    DESTINACAO_PAD VARCHAR2(60) NOT NULL,
    PERICULOSIDADE VARCHAR2(20) NOT NULL
);

CREATE TABLE COLETOR (
    ID_COLETOR NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_SETOR NUMBER(10) NOT NULL,
    ID_TIPO NUMBER(10) NOT NULL,
    CODIGO VARCHAR2(20) UNIQUE NOT NULL,
    LOCALIZACAO VARCHAR2(150) NOT NULL,
    CAPACIDADE_LT NUMBER(10,2) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    DT_INSTALACAO DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_COL_SETOR FOREIGN KEY (ID_SETOR) REFERENCES SETOR(ID_SETOR),
    CONSTRAINT FK_COL_TIPO FOREIGN KEY (ID_TIPO) REFERENCES TIPO_RESIDUO(ID_TIPO)
);

CREATE TABLE REGISTRO_VOLUME (
    ID_REGISTRO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_COLETOR NUMBER(10) NOT NULL,
    VOLUME_LT NUMBER(10,2) NOT NULL,
    PERCENTUAL_USO NUMBER(5,2),
    ORIGEM_LEITURA VARCHAR2(20) NOT NULL,
    DT_LEITURA DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_RV_COLETOR FOREIGN KEY (ID_COLETOR) REFERENCES COLETOR(ID_COLETOR)
);

CREATE TABLE ORDEM_COLETA (
    ID_ORDEM NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_COLETOR NUMBER(10) NOT NULL,
    DESTINACAO VARCHAR2(60) NOT NULL,
    ORIGEM_ORDEM VARCHAR2(20) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    DT_ABERTURA DATE DEFAULT SYSDATE NOT NULL,
    DT_CONCLUSAO DATE,
    OBSERVACAO VARCHAR2(300),
    CONSTRAINT FK_OC_COLETOR FOREIGN KEY (ID_COLETOR) REFERENCES COLETOR(ID_COLETOR)
);

CREATE TABLE ALERTA_COLETOR (
    ID_ALERTA NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_COLETOR NUMBER(10) NOT NULL,
    TIPO_ALERTA VARCHAR2(30) NOT NULL,
    MENSAGEM VARCHAR2(500) NOT NULL,
    PERCENTUAL_USO NUMBER(5,2),
    DT_ALERTA DATE DEFAULT SYSDATE NOT NULL,
    LIDO CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT FK_AL_COLETOR FOREIGN KEY (ID_COLETOR) REFERENCES COLETOR(ID_COLETOR)
);