-- Seed inicial para desenvolvimento

INSERT INTO SETOR (NOME_SETOR, DESCRICAO, RESPONSAVEL)
VALUES ('Setor A', 'Linha de producao principal', 'Ana Souza');

INSERT INTO SETOR (NOME_SETOR, DESCRICAO, RESPONSAVEL)
VALUES ('Setor B', 'Area de embalagem', 'Bruno Lima');

INSERT INTO TIPO_RESIDUO (NOME_RESIDUO, CLASSIFICACAO, DESTINACAO_PAD, PERICULOSIDADE)
VALUES ('Plastico', 'RECICLAVEL', 'Reciclagem', 'BAIXA');

INSERT INTO TIPO_RESIDUO (NOME_RESIDUO, CLASSIFICACAO, DESTINACAO_PAD, PERICULOSIDADE)
VALUES ('Organico', 'ORGANICO', 'Compostagem', 'BAIXA');

INSERT INTO COLETOR (ID_SETOR, ID_TIPO, CODIGO, LOCALIZACAO, CAPACIDADE_LT, STATUS)
VALUES (
    (SELECT ID_SETOR FROM SETOR WHERE NOME_SETOR = 'Setor A'),
    (SELECT ID_TIPO FROM TIPO_RESIDUO WHERE NOME_RESIDUO = 'Plastico'),
    'COL-001',
    'Linha de Producao - Setor A',
    200.00,
    'ATIVO'
);

INSERT INTO COLETOR (ID_SETOR, ID_TIPO, CODIGO, LOCALIZACAO, CAPACIDADE_LT, STATUS)
VALUES (
    (SELECT ID_SETOR FROM SETOR WHERE NOME_SETOR = 'Setor B'),
    (SELECT ID_TIPO FROM TIPO_RESIDUO WHERE NOME_RESIDUO = 'Organico'),
    'COL-002',
    'Area de Embalagem - Setor B',
    150.00,
    'ATIVO'
);

INSERT INTO REGISTRO_VOLUME (ID_COLETOR, VOLUME_LT, PERCENTUAL_USO, ORIGEM_LEITURA)
VALUES (
    (SELECT ID_COLETOR FROM COLETOR WHERE CODIGO = 'COL-001'),
    120.00,
    60.00,
    'MANUAL'
);

INSERT INTO REGISTRO_VOLUME (ID_COLETOR, VOLUME_LT, PERCENTUAL_USO, ORIGEM_LEITURA)
VALUES (
    (SELECT ID_COLETOR FROM COLETOR WHERE CODIGO = 'COL-002'),
    90.00,
    60.00,
    'MANUAL'
);

INSERT INTO ORDEM_COLETA (ID_COLETOR, DESTINACAO, ORIGEM_ORDEM, STATUS, OBSERVACAO)
VALUES (
    (SELECT ID_COLETOR FROM COLETOR WHERE CODIGO = 'COL-001'),
    'Reciclagem',
    'SISTEMA',
    'ABERTA',
    'Ordem gerada automaticamente'
);

INSERT INTO ALERTA_COLETOR (ID_COLETOR, TIPO_ALERTA, MENSAGEM, PERCENTUAL_USO, LIDO)
VALUES (
    (SELECT ID_COLETOR FROM COLETOR WHERE CODIGO = 'COL-002'),
    'CAPACIDADE',
    'Coletor acima de 80% de uso',
    82.50,
    'N'
);

