CREATE TABLE USUARIO (
    ID_USUARIO NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(30) NOT NULL
);
